modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Unhealthy-Dying/issues"
license="MIT"

[[mods]]
modId="unhealthydying"
version="${file.jarVersion}"
displayName="Unhealthy Dying"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unhealthy-dying"
authors="Mrbysco"
credits="rubisnosetti for the mod idea"
logoFile="logo.png"
description='''Losing health from dying'''
[[dependencies.unhealthydying]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.unhealthydying]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"