# Project
version=3.3.0
group=com.mrbysco.unhealthydying

# Common
minecraft_version=1.21.4
neoform_version=1.21.4-20241203.161809
parchment_minecraft_version=1.21.4
parchment_mapping_version=2025.03.23

# NeoForge
neo_version=21.4.149

# Fabric
fabric_version=0.119.4+1.21.4
fabric_loader_version=0.17.2
cloth_config_version=17.0.144
mod_menu_version=13.0.3

# Mod options
mod_name=UnhealthyDying
mod_author=Mrbysco
mod_id=unhealthydying

#Publishing
curseforge_id=307753
modrinth_id=pxMdk6aB

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false