modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Mrbysco/Unhealthy-Dying/issues"

[[mods]]
modId="unhealthydying"
version="${file.jarVersion}"
displayName="Unhealthy Dying"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unhealthy-dying"
authors="Mrbysco"
credits="rubisnosetti for the mod idea"
logoFile="logo.png"
description='''Losing health from dying'''