modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Unhealthy-Dying/issues"
license="MIT"

[[mods]]
modId="unhealthydying"
version="${file.jarVersion}"
displayName="Unhealthy Dying"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unhealthy-dying"
authors="Mrbysco"
credits="rubisnosetti for the mod idea"
logoFile="logo.png"
description='''Losing health from dying'''

[[dependencies.unhealthydying]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.5,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.unhealthydying]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.5.0-beta,)"
ordering="NONE"
side="BOTH"